### ISSUE TITLE
Story 2 - Improve the quality of the questions generated; comparing with known good samples

### ISSUE THREAD

**Issue by Exortix** [bahrain-uob/moe-questions-bank#26]
This story is to ensure that the output of the LLM meets the minimum quality standards in order to be used as questions in an actual exam.

- [x] #27
- [x] #28
- [x] #29
- [x] #30
- [x] #42
- [x] #43
- [x] #31
    - [x] Competency
    - [x] Difficulty
    - [x] Time per question
    - [x] Average duration of the exam (as estimated by the LLM)
    - [x] Deviation from the ideal
- [x] #32
    - [x] Reflect the key pairs in the prompt @Ebrahim23m 
    - [x] Connect to the endpoint of the bedrock model. @Mahmood-Almarzooq 
    - [x] Agree on the exam display format. @fatima-526 
    - [x] Format the exam. @fatima-526 
    - [x] Introduce the quality evaluation of the exam.

**Comment by BaselMalalla** [comment]
I was unable to create a bedrock knowledge base in the Ireland region (eu-west-1) due to missing access to embedding models. A similar issue in N. Virginia (us-east-1) was resolved after requesting access, but the "Request Access" button is missing in Ireland.

Actions taken:
1. Opened a support case with AWS to request embedding model access in Ireland.
2. Proceeded with N. Virginia temporarily to avoid delays.
