### ISSUE TITLE
Experiment with fine tuning/continued pre-training for Arabic

### ISSUE THREAD

**Issue by Mahmood-Almarzooq** [bahrain-uob/moe-questions-bank#79]

**Comment by BaselMalalla** [comment]
- Fine-tuning requires structured data, which we don’t have.
- Structuring the data isn’t feasible, so I ruled out Fine-tuning.
- For continued pre-training we need the data in text, and then we should plug it into samples each 4096 tokens, a token is approximately 6 characters
- Another challenge is extracting text from PDFs. The textbooks encoding made the output incomprehensible (e.g., π˘YÉ˘Ø˘J ø˘e ≥˘∏˘£˘æ˘j...). and some of them don't even contain selectable text.
- We could try using Arabic OCR to extract the text from the PDFs.
- However, Arabic OCRs often perform poorly based on my experience.
- Also we can only use the model "Amazon Titan Text G1 - Express", since it is the only model on Bedrock that supports continuous pre-training and Arabic language. (we're going SST so we must stick to Bedrock)

My judgment:
-  Given the uncertainty of Arabic OCR performance,
- And the uncertainty of the models performance after the training,
- I think our time is better spent elsewhere for now.
- we can get back to it if we have extra time later on.
